name: NPM Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: 
    
    
jobs:
  main:
    uses: deep-foundation/workflows/.github/workflows/npm-test.yml@main
